### ISSUE TITLE
Homepage LXC Script installation error

### ISSUE THREAD

**Issue by Michi1983** [community-scripts/ProxmoxVE#1118]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

homepage.sh

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/homepage.sh)"

### 📝 Provide a clear and concise description of the issue.

Installation stops with the error 
`
[ERROR] in line 46: exit code 0: while executing command $STD NEXT_PUBLIC_VERSION=v$RELEASE NEXT_PUBLIC_REVISION='source' pnpm build 
`

### ⚙️ What settings are you using?

- [ ] Default Settings
- [X] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 12

### 🔄 Steps to reproduce the issue.

Run script
Answer all questions 
Error come up

### ❌ Paste the full error output (if available).

`
devDependencies:
+ @tailwindcss/forms 0.5.9
+ autoprefixer 10.4.20
+ eslint 8.57.1
+ eslint-config-airbnb 19.0.4
+ eslint-config-next 14.2.8
+ eslint-config-prettier 9.1.0
+ eslint-plugin-import 2.31.0
+ eslint-plugin-jsx-a11y 6.10.0
+ eslint-plugin-prettier 5.2.1
+ eslint-plugin-react 7.37.2
+ eslint-plugin-react-hooks 4.6.2
+ postcss 8.4.47
+ prettier 3.3.3
+ tailwind-scrollbar 3.1.0
+ tailwindcss 3.4.14
+ typescript 5.6.3

Done in 18.9s
 ⠋bash: line 46: NEXT_PUBLIC_VERSION=v0.10.6: command not found

[ERROR] in line 46: exit code 0: while executing command $STD NEXT_PUBLIC_VERSION=v$RELEASE NEXT_PUBLIC_REVISION='source' pnpm build
`

**Comment by MickLesk** [comment]
Can you try again?

**Comment by desmondfuller** [comment]
I had tried it this AM and it did not work.  I just tried it now (after seeing this) and it worked perfectly.  Thank you

**Comment by Lampan-git** [comment]
It fails to start the service now: 
```
homepage systemd[1]: Started homepage.service - Homepage.
homepage pnpm[4112]: > homepage@0.9.6 start /opt/homepage
homepage pnpm[4112]: > next start
homepage pnpm[4186]: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
homepage pnpm[4186]: Error: Could not find a production build in the '/opt/homepage/.next' directory. Try building your app with 'next build' before starting the production server. https://next>
homepage pnpm[4186]:     at NextNodeServer.getBuildId (/opt/homepage/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:169:>
homepage pnpm[4186]:     at new Server (/opt/homepage/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:58:29)
homepage pnpm[4186]:     at new NextNodeServer (/opt/homepage/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:70:9)
homepage pnpm[4186]:     at NextServer.createServer (/opt/homepage/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next.js:140:16)
homepage pnpm[4186]:     at async /opt/homepage/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next.js:149:31
homepage pnpm[4112]:  ELIFECYCLE  Command failed with exit code 1.
homepage systemd[1]: homepage.service: Main process exited, code=exited, status=1/FAILURE
homepage systemd[1]: homepage.service: Failed with result 'exit-code'.
```

**Comment by Michi1983** [comment]
I have testet it again, but It looks like the same error.

`
devDependencies:
+ @tailwindcss/forms 0.5.9
+ autoprefixer 10.4.20
+ eslint 8.57.1
+ eslint-config-airbnb 19.0.4
+ eslint-config-next 14.2.8
+ eslint-config-prettier 9.1.0
+ eslint-plugin-import 2.31.0
+ eslint-plugin-jsx-a11y 6.10.0
+ eslint-plugin-prettier 5.2.1
+ eslint-plugin-react 7.37.2
+ eslint-plugin-react-hooks 4.6.2
+ postcss 8.4.47
+ prettier 3.3.3
+ tailwind-scrollbar 3.1.0
+ tailwindcss 3.4.14
+ typescript 5.6.3

Done in 18.4s
 ⠦bash: line 46: NEXT_PUBLIC_VERSION=v0.10.6: command not found

[ERROR] in line 46: exit code 0: while executing command $STD NEXT_PUBLIC_VERSION=v$RELEASE
`

Did I do something wrong?

**Comment by MickLesk** [comment]
Idk, its an PR from another Dude Yesterday. I can revert it completly to older script

**Comment by MickLesk** [comment]
removed now

**Comment by Michi1983** [comment]
Perfect thank you, it works now.

**Comment by se-bastiaan** [comment]
> Idk, its an PR from another Dude Yesterday. I can revert it completly to older script

This dude has a name and you are allowed to hold him accountable if he breaks something :)
Next time it would be better to revert the original PR from GitHub and reopen the issue, this way you don't trigger any notification and if I weren't looking into something else I wouldn't have noticed this.

Can we still reopen the original issue maybe so I can look into this later?

**Comment by MickLesk** [comment]
> This dude has a name and you are allowed to hold him accountable if he breaks something :) Next time it would be better to revert the original PR from GitHub and reopen the issue, this way you don't trigger any notification and if I weren't looking into something else I wouldn't have noticed this.
> 
> Can we still reopen the original issue maybe so I can look into this later?



yes i just commented and fixed it yesterday on my phone because i wasn't at the pc ^^ don't know the original bug or customization request.

If you have a fix, please try running it against the develop branch. I don't use the script, so it's hard for me to understand.
