### ISSUE TITLE
zigbee2mqtt update crash

### ISSUE THREAD

**Issue by polter05** [community-scripts/ProxmoxVE#454]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

After update, zigbee don't start. With start with cli "zigbee2mqtt" -> this message 👍 

Error relocating /usr/lib/zigbee2mqtt/node_modules/unix-dgram/build/Release/unix_dgram.node: _ZN2v820EscapableHandleScopeC1EPNS_7IsolateE: symbol not found

An idea ?

### What settings are you currently utilizing?

- [X] Default Settings
- [ ] Advanced Settings

### Which Linux distribution are you employing?

Alpine

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
alpine-zigbee2mqtt:~# zigbee2mqtt 
Starting Zigbee2MQTT without watchdog.
[2024-11-23 09:27:12] info:     z2m: Logging to console, syslog
Error: Error relocating /usr/lib/zigbee2mqtt/node_modules/unix-dgram/build/Release/unix_dgram.node: _ZN2v820EscapableHandleScopeC1EPNS_7IsolateE: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1715:18)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at bindings (/usr/lib/zigbee2mqtt/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/lib/zigbee2mqtt/node_modules/unix-dgram/lib/unix_dgram.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
```

### Please provide detailed steps to reproduce the issue.

After run

bash -c "$(wget -qO - https://github.com/tteck/Proxmox/raw/main/ct/alpine-zigbee2mqtt.sh)"

or

bash -c "$(wget -qO - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/alpine-zigbee2mqtt.sh)"

**Comment by gionag** [comment]
i can confirm, also on my alpine it does that.

**Comment by MickLesk** [comment]
This looks very much like a bug in Zigbee2MQTT itself, i.e. in the Alpine package.

Can you try the following? -- PLEASE MAKE A BACKUP OF THE WHOLE LXC FIRST! -- 
```bash
apk del zigbee2mqtt
apk add zigbee2mqtt --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
zigbee2mqtt --version
